version: "3.8"
services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    container_name: frontend_c
    restart: always
    ports:
      - "5173:5173"
  backend:
    build: ./backend
    restart: always
    depends_on:
      - mysqldb
    container_name: backend_c
    links:
      - mysqldb
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=origin_db
    ports:
      - "3307:3306"
