version: "3.8"
services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    container_name: frontend_c
    restart: always
    ports:
      - "5173:5173"
  backend:
    build: ./backend
    env_file:
      - .env
    restart: always
    depends_on:
      - mysqldb
    container_name: backend_c
    links:
      - mysqldb
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
  mysqldb:
    image: mysql
    env_file:
      - .env
    restart: always
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
